[build]
  command = "npm install && npm run build"
  publish = "build"
  package_manager = "npm" # Ensure Netlify uses npm instead of pnpm

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18.20.4" # Ensure this matches the Node.js version you are using locally
