[build]
  command = "pnpm install && pnpm run build"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  package_manager = "pnpm"
