[build]
  command = "npm install && npm run build"
  publish = "build"
  package_manager = "npm" # This ensures Netlify uses npm instead of pnpm

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
